"""Move Profile model to profile app

Revision ID: 0274408c8f43
Revises: 0631b3847473
Create Date: 2025-07-18 10:20:38.942225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0274408c8f43'
down_revision: Union[str, Sequence[str], None] = '0631b3847473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('weight_unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'weight_unit')
    # ### end Alembic commands ###
