"""Add profile_picture_url field

Revision ID: 0c73d828d89e
Revises: 0274408c8f43
Create Date: 2025-07-18 12:15:02.248226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c73d828d89e'
down_revision: Union[str, Sequence[str], None] = '0274408c8f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'profile_picture_url')
    # ### end Alembic commands ###
