"""Add llm_generated_filename field to Document model

Revision ID: 0d9457d45c69
Revises: c21197569db7
Create Date: 2025-08-04 13:05:20.225440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9457d45c69'
down_revision: Union[str, Sequence[str], None] = 'c21197569db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('llm_generated_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'llm_generated_filename')
    # ### end Alembic commands ###
