"""removed unique from the keyword

Revision ID: 66db40590f53
Revises: 5b2b07ec3d77
Create Date: 2025-09-09 11:44:55.040462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66db40590f53'
down_revision: Union[str, Sequence[str], None] = '5b2b07ec3d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_keyword'), table_name='translations')
    op.create_index(op.f('ix_translations_keyword'), 'translations', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_keyword'), table_name='translations')
    op.create_index(op.f('ix_translations_keyword'), 'translations', ['keyword'], unique=True)
    # ### end Alembic commands ###
