"""Add is_deleted field to users table

Revision ID: 989b24221cfb
Revises: 66db40590f53
Create Date: 2025-09-10 15:42:03.234976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989b24221cfb'
down_revision: Union[str, Sequence[str], None] = '66db40590f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable with a default value
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    
    # Update existing rows to have is_deleted = False
    op.execute("UPDATE users SET is_deleted = FALSE WHERE is_deleted IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('users', 'is_deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
