"""add is_out_of_scope to chat_messages

Revision ID: 9aedd42931b8
Revises: 54a05f5e2ebd
Create Date: 2025-08-12 13:23:52.955686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aedd42931b8'
down_revision: Union[str, Sequence[str], None] = '54a05f5e2ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_out_of_scope', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'is_out_of_scope')
    # ### end Alembic commands ###
