"""add_mid_to_chat_messages_and_rename_chat_id_to_conv_id

Revision ID: 9d8d88b301ce
Revises: a94a8ce888f8
Create Date: 2025-08-01 14:02:52.065515

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8d88b301ce'
down_revision: Union[str, Sequence[str], None] = 'a94a8ce888f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add mid column to chat_messages
    op.add_column('chat_messages', sa.Column('mid', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_chat_messages_mid'), 'chat_messages', ['mid'], unique=True)
    
    # Update existing chat_messages to have mid values
    connection = op.get_bind()
    chat_messages = connection.execute(sa.text("SELECT id FROM chat_messages")).fetchall()
    for msg in chat_messages:
        connection.execute(
            sa.text("UPDATE chat_messages SET mid = :mid WHERE id = :id"),
            {"mid": str(uuid.uuid4()), "id": msg[0]}
        )
    
    # Make mid column not nullable after populating
    op.alter_column('chat_messages', 'mid', nullable=False)
    
    # Add conv_id column to conversations
    op.add_column('conversations', sa.Column('conv_id', sa.UUID(as_uuid=False), nullable=True))
    
    # Copy data from chat_id to conv_id
    connection.execute(sa.text("UPDATE conversations SET conv_id = chat_id"))
    
    # Make conv_id not nullable after copying data
    op.alter_column('conversations', 'conv_id', nullable=False)
    
    # Create new index for conv_id
    op.create_index(op.f('ix_conversations_conv_id'), 'conversations', ['conv_id'], unique=True)
    
    # Drop old chat_id column and index
    op.drop_index(op.f('ix_conversations_chat_id'), table_name='conversations')
    op.drop_column('conversations', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add back chat_id column
    op.add_column('conversations', sa.Column('chat_id', sa.UUID(as_uuid=False), nullable=True))
    
    # Copy data back from conv_id to chat_id
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE conversations SET chat_id = conv_id"))
    
    # Make chat_id not nullable
    op.alter_column('conversations', 'chat_id', nullable=False)
    
    # Create old index
    op.create_index(op.f('ix_conversations_chat_id'), 'conversations', ['chat_id'], unique=True)
    
    # Drop new conv_id column and index
    op.drop_index(op.f('ix_conversations_conv_id'), table_name='conversations')
    op.drop_column('conversations', 'conv_id')
    
    # Drop mid column and index
    op.drop_index(op.f('ix_chat_messages_mid'), table_name='chat_messages')
    op.drop_column('chat_messages', 'mid')
    # ### end Alembic commands ###
