"""add_icon_path_to_prompts

Revision ID: a647a8b355c8
Revises: 0d9457d45c69
Create Date: 2025-08-04 15:43:56.316922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a647a8b355c8'
down_revision: Union[str, Sequence[str], None] = '0d9457d45c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('icon_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'icon_path')
    # ### end Alembic commands ###
