"""user table args commented

Revision ID: b50ba96f04a4
Revises: 989b24221cfb
Create Date: 2025-09-10 17:03:15.203348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50ba96f04a4'
down_revision: Union[str, Sequence[str], None] = '989b24221cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_country_mobile'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_country_mobile'), 'users', ['country_code', 'mobile_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
