"""Add is_deletable field to Translation model

Revision ID: c7288d848318
Revises: 8dcd6a85803f
Create Date: 2025-09-08 12:06:33.032507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7288d848318'
down_revision: Union[str, Sequence[str], None] = '8dcd6a85803f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('is_deletable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translations', 'is_deletable')
    # ### end Alembic commands ###
