"""Add composite unique constraint to users

Revision ID: f1945380ff0b
Revises: 0c73d828d89e
Create Date: 2025-07-23 15:12:10.752943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1945380ff0b'
down_revision: Union[str, Sequence[str], None] = '0c73d828d89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_country_mobile', 'users', ['country_code', 'mobile_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_country_mobile', 'users', type_='unique')
    # ### end Alembic commands ###
